name: Some nice testing if we can build to Container Registry
on:
  push:
    branches:
      - staging

jobs:
  build_and_push:
    runs-on: self-hosted

    name: 'Build and push the image'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'

      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'glo-tech-dev-sebas'
          export_default_credentials: true

      - name: 'Configure Docker client'
        run: |
          gcloud auth configure-docker --quiet

      - name: 'Build and push'
        run: |
          gcloud builds submit --tag gcr.io/glo-tech-dev-sebas/dqna-cloud:staging .
